### ISSUE TITLE
weed is not drying on the drying post

### ISSUE THREAD

**Issue by bluecollarboysgaming** [42MonthsAfter/Start-Here#4]
Pve server weed is put on the post and wont dry

**Comment by BnYrB** [comment]
I just tested and it appears to be working for me. You have to make sure you activate the drying post by hitting F  and "leave for drying"

**Comment by BnYrB** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/8458331/211200475-5124f102-49b5-439e-890c-11c6b15c9dac.png)

**Comment by BnYrB** [comment]
Did this resolve this @bluecollarboysgaming ??

**Comment by bluecollarboysgaming** [comment]
Yes
